"""
Coverage A: ablation reproducibility.

We established in results/ANALYSIS.md that these experiments are NOT
bit-reproducible -- re-running experiment 4's identical script (same seed,
same hyperparameters) produced a different best-epoch accuracy the second
time (98.17% vs 99.42%). See test_seeds_are_set below and the
"Nondeterminism" section of ANALYSIS.md for why.

Given that, these tests do NOT retrain anything and do NOT assert exact
values. They load the JSON results already committed to
results/investigation/ and assert the DIRECTIONAL conclusion the whole
investigation rests on: momentum-default configs land near chance,
momentum-fixed configs land near-ceiling. That gap (roughly 0.5 vs 0.99+
ROC-AUC) is over 100x larger than the run-to-run swing observed in the
head-depth comparison, so it is not sensitive to the nondeterminism that
makes the head-depth question itself unresolvable (see ANALYSIS.md SS1).
"""
import json

import pytest

from conftest import INVESTIGATION_DIR

# Below this, a config is "chance-adjacent" (random guessing = 0.5 AUC).
CHANCE_ADJACENT_AUC = 0.80
# Above this, a config has recovered to near-ceiling performance.
NEAR_CEILING_AUC = 0.99


def _load(filename):
    path = INVESTIGATION_DIR / filename
    if not path.exists():
        pytest.skip(f"{filename} not found in results/investigation/")
    return json.loads(path.read_text())


class TestMomentumDefaultConfigsLandNearChance:
    """Experiments 1 & 2: Keras BatchNormalization at its default
    momentum=0.99. Both should be well below near-ceiling, regardless of
    head depth -- this is the "broken" side of the ablation."""

    def test_experiment1_original_head_default_momentum(self):
        data = _load("m2l1_anomaly_result.json")
        assert data["final_roc_auc"] < CHANCE_ADJACENT_AUC, (
            f"Experiment 1 (original head, default momentum) scored "
            f"{data['final_roc_auc']:.4f} ROC-AUC -- expected chance-adjacent "
            f"(< {CHANCE_ADJACENT_AUC}). If this now passes with a high score, "
            f"the underlying JSON may have been regenerated by a fixed run; "
            f"re-check which experiment produced it."
        )

    def test_experiment2_simplified_head_default_momentum(self):
        data = _load("m2l1_anomaly_result2_simplified_head.json")
        assert data["final_roc_auc"] < CHANCE_ADJACENT_AUC, (
            f"Experiment 2 (simplified head, default momentum) scored "
            f"{data['final_roc_auc']:.4f} ROC-AUC -- expected chance-adjacent "
            f"(< {CHANCE_ADJACENT_AUC})."
        )


class TestMomentumFixedConfigsSaturate:
    """Experiments 3 & 4: BatchNormalization(momentum=0.9). Both should be
    near-ceiling under EITHER epoch-selection convention -- this is the
    "fixed" side of the ablation, and the point of ANALYSIS.md SS1's central
    claim (experiment 1 vs. 4, holding architecture constant)."""

    def test_experiment3_simplified_head_fixed_momentum(self):
        data = _load("m2l1_anomaly_result3_bn_momentum.json")
        assert data["last_epoch_metrics"]["roc_auc"] > NEAR_CEILING_AUC
        assert data["best_epoch_metrics"]["roc_auc"] > NEAR_CEILING_AUC

    def test_experiment4_original_head_fixed_momentum(self):
        data = _load("m2l1_anomaly_result4_original_head_bn_fix.json")
        assert data["last_epoch_metrics"]["roc_auc"] > NEAR_CEILING_AUC
        assert data["best_epoch_metrics"]["roc_auc"] > NEAR_CEILING_AUC


class TestMomentumIsTheDominantEffect:
    """The controlled isolation: experiment 1 vs. 4, identical architecture
    (original 6-block head), only momentum changed. This is the primary
    finding of the whole investigation and does not depend on which
    epoch-selection convention is used -- experiment 1 never leaves the
    chance-adjacent range at any epoch (see ANALYSIS.md SS1)."""

    def test_fixing_momentum_alone_closes_the_gap(self):
        exp1 = _load("m2l1_anomaly_result.json")
        exp4 = _load("m2l1_anomaly_result4_original_head_bn_fix.json")

        broken_auc = exp1["final_roc_auc"]
        fixed_auc_last = exp4["last_epoch_metrics"]["roc_auc"]
        fixed_auc_best = exp4["best_epoch_metrics"]["roc_auc"]

        gap_last = fixed_auc_last - broken_auc
        gap_best = fixed_auc_best - broken_auc

        # The effect size is the entire point: a ~0.48 AUC jump from a single
        # parameter change, on identical architecture. This is not a subtle
        # difference that borderline thresholds could get wrong either way.
        assert gap_last > 0.4, f"Expected a large gap, got {gap_last:.4f}"
        assert gap_best > 0.4, f"Expected a large gap, got {gap_best:.4f}"


def test_seeds_are_set_in_experiment_scripts():
    """Documents (does not merely assert) that all four experiment scripts
    seed python's random, numpy, and TensorFlow's global seed, plus pass an
    explicit seed to Keras's flow_from_directory. Despite this, re-running
    experiment 4's script produced different results run to run (see
    ANALYSIS.md SS1, "Nondeterminism"). That combination -- seeds set,
    results still vary -- is the signature of TensorFlow CPU op-level
    nondeterminism (multi-threaded floating-point reduction order in
    convolution/BatchNorm kernels), which `tf.random.set_seed` does not
    control. This is a documentation test: if it ever fails, the scripts
    have drifted from what ANALYSIS.md describes and the limitation note
    needs to be revisited, not the other way around.
    """
    script_dir = INVESTIGATION_DIR
    scripts = sorted(script_dir.glob("m2l1_anomaly_experiment*.py"))
    assert len(scripts) == 4, f"Expected 4 experiment scripts, found {len(scripts)}"

    for script in scripts:
        source = script.read_text(encoding="utf-8")
        assert "random.seed(SEED)" in source, f"{script.name} missing python random seed"
        assert "np.random.seed(SEED)" in source, f"{script.name} missing numpy seed"
        assert "tf.random.set_seed(SEED)" in source, f"{script.name} missing TF global seed"
        assert "seed=SEED" in source, f"{script.name} missing seed= on flow_from_directory"
        # None of the scripts enable TF's op-level determinism mode -- this is
        # WHY results still vary despite the seeds above. Not adding it here
        # retroactively, since doing so would invalidate the recorded results
        # this test suite is checking against.
        assert "enable_op_determinism" not in source
